### ISSUE TITLE
Feat: 로그인 기능 개발

### ISSUE THREAD

**Issue by sjsjsj1246** [project-refri/refri-mobile#9]
## Description

- OAuth 기반의 로그인 기능을 개발합니다.
- firebase Authentication 기능을 이용합니다.
  - 공급업체: Google, Apple

## Todo

- [ ] Firebase API 이용 구글, 애플 OAuth 인증
- [ ] 리프리 API 서버를 이용해 리프리 서비스 사용자 인증
- [ ] 리프리 서비스 인증 정보 유지

## References

https://firebase.google.com/docs/auth/flutter/start?hl=ko&authuser=0
